# Generated by Django 5.2.10 on 2026-01-27 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0012_role_can_manage_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='General Meeting', max_length=200)),
                ('date', models.DateTimeField()),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global (All Members)'), ('SIG', 'SIG Specific'), ('CUSTOM', 'Custom Selection')], default='GLOBAL', max_length=20)),
                ('target_years', models.JSONField(blank=True, default=list, help_text='List of years [1, 2, 3, 4] included. Empty = All.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open (Marking in progress)'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_sessions', to=settings.AUTH_USER_MODEL)),
                ('target_sigs', models.ManyToManyField(blank=True, help_text='If scope is SIG, which SIGs?', related_name='attendance_sessions', to='users.sig')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='ABSENT', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
            options={
                'unique_together': {('session', 'user')},
            },
        ),
    ]
