# Generated by Django 5.2.10 on 2026-01-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_teamposition_role_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_messages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_sponsorship',
            field=models.BooleanField(default=False),
        ),
    ]
