# Generated by Django 5.2.10 on 2026-01-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_role_can_manage_messages_role_can_manage_sponsorship'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_forms',
            field=models.BooleanField(default=False),
        ),
    ]
