# Generated by Django 5.2.10 on 2026-01-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_deadline_projectthread_threadmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectthread',
            name='is_ephemeral',
            field=models.BooleanField(default=False, help_text='If true, messages self-destruct after delivery/time'),
        ),
    ]
