# Generated by Django 5.2.10 on 2026-01-24 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Single Answer'), ('MSQ', 'Multiple Select Questions')], default='MCQ', max_length=10)),
                ('marks', models.FloatField()),
                ('negative_marks', models.FloatField(default=0)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quizzes.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('join_code', models.CharField(help_text='Code required to enter the quiz', max_length=20, unique=True)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('auto_submit_on_tab_switch', models.BooleanField(default=True)),
                ('require_fullscreen', models.BooleanField(default=True)),
                ('disable_right_click', models.BooleanField(default=True)),
                ('default_marks', models.FloatField(default=4.0)),
                ('default_negative_marks', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STARTING', 'Questionnaire Phase'), ('ONGOING', 'Quiz in Progress'), ('SUBMITTED', 'Manually Submitted'), ('AUTO_SUBMITTED', 'Auto Submitted (Timer)'), ('DISQUALIFIED', 'Disqualified (Proctoring Violation)')], default='STARTING', max_length=20)),
                ('questionnaire_data', models.JSONField(blank=True, default=dict)),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('score', models.FloatField(default=0.0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('quiz', 'user')},
            },
        ),
    ]
