# Generated by Django 5.2.10 on 2026-01-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_question_question_type_alter_quizattempt_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
