# Generated by Django 5.2.10 on 2026-01-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_form_theme_alter_formfield_field_type_formsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='closes_at',
            field=models.DateTimeField(blank=True, help_text='Automatic closure timestamp', null=True),
        ),
    ]
